### ISSUE TITLE
Unable to locate executable file: gigalixir

### ISSUE THREAD

**Issue by forest** [mhanberg/gigalixir-action#32]
I'm getting the following error with `gigalixir-action@v0.4.3`.

Any ideas?

Error: Unable to locate executable file: gigalixir. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by mhanberg** [comment]
Can you share your workflow configuration?

**Comment by forest** [comment]
```
  deploy:
    name: Deploy to Gigalixir
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: next # Checkout out next instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
      - uses: mhanberg/gigalixir-action@v0.4.3
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_EMAIL }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: ${{ secrets.GIGALIXIR_APP_NAME }}
          SSH_PRIVATE_KEY: "no"
          MIGRATIONS: false
```

Maybe it doesn't like `ubuntu-latest`?
